name: crawl data

on: 
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * *
    
jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout actions
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Install Dependencies
      run: pip install scrapy
      
    - name: Crawl
      run: |
        cd dataFetcher
        scrapy crawl ncov2019
        
    - name: Commit & Push
      run: |
        git config --global user.email 52402142+rei-smz@users.noreply.github.com
        git config --global user.name Rin Shimizu
        git add .
        git commit -m "update data" -a
        git push
        
